## 1.2 Coding exercise 1
from typing import Pattern


test_text = """TTCATATGCTATACTTCATATTTCATATACTTTCCAGGTTCATATGATTTCATATGTTCATATTTCATATTTGTTTCATATGCTTCATATTATTCATATTATTCATATGTTTCATATTTCGTTCATATGTTCATATTTCATATTTCATATTGTTCATATTAAAGTTCATATAAATCGTTCATATGTTCATATAGTTATCCGTGTTCATATGCCATTTTTCATATTGTTTCATATTGTTATATTTCATATAGTTCATATCCATTCATATGACTCCATTTCATATGGTTTATATTCATATTTTCATATATATTCATATCTTTTCATATAACTTCATATCTTCATATCTCTCGTTCATATTCGTTCATATTGGCTTCATATGTTCATATGCGTTCATATTTTCATATGATTCATATTTCGTTTCATATGTTCATATAGATTCATATGTTCATATTTCATATTTTCATATGTTCATATTAGCTTCATATTTCATATTTCATATTTCATATAATAAATTCATATAAAGTTTCATATCCGCGTTCATATGCATTCATATCTATACCTTCATATTTCATATGCAGGAGACATACCTCGAATTCATATTTCATATTTTTTCATATGCCTTTCATATTTCATATGATAGGCAAAGTTCATATGAAGCCTATTCATATTTCATATTTCATATATTTTCATATCTGTTCATATCTTCATATTCTATTCATATTTCATATGGTTCATATCTTTCATATATTTCATATGGTTGTTTCATATTTCATATGCTTCATATTTCATATTTCATATCTTCATATTTCATATTTTACTTTCATATTTCATATCCCGCGGGTTCATATATTCATATTTCATATTGTTCATATATTCTTCATATTTTCATATTTTCATATTTCATATTTCATATTTCATATTTCATATTTCATATTTTCATATATAGCTTCATATTATTCATATTTCATATGTTCATATGCTTCATATCGCTTCATATC"""
test_pattern = "TTCATATTT"

def PatternCount(text, pattern):
    """This is a redundant piece of code for the string method.count()"""
    count = 0
    pattern_length = len(pattern)
    difference = len(text) - pattern_length
    for ind in range(0, difference):
        if text[ind:ind+pattern_length] == pattern:
            count = count + 1
    return(count)

result = PatternCount(test_text, test_pattern)
print(result)
